-- CreateTable
CREATE TABLE `Fixture` (
    `id` BIGINT NOT NULL,
    `competition_id` BIGINT NOT NULL,
    `competition_name` VARCHAR(191) NULL,
    `sport_alias` VARCHAR(191) NOT NULL,
    `sport_name` VARCHAR(191) NULL,
    `status` VARCHAR(191) NULL,
    `scheduled_start_time` BIGINT NULL,
    `start_time` BIGINT NULL,
    `end_time` BIGINT NULL,
    `tie` INTEGER NULL,
    `winner_id` BIGINT NULL,
    `participants0_id` BIGINT NULL,
    `participants0_name` VARCHAR(191) NULL,
    `participants0_score` INTEGER NULL,
    `participants1_id` BIGINT NULL,
    `participants1_name` VARCHAR(191) NULL,
    `participants1_score` INTEGER NULL,
    `hs_description` VARCHAR(191) NULL,
    `rr_description` VARCHAR(191) NULL,
    `manual_override` INTEGER NULL,
    `manual_updated_at` DATETIME(3) NULL,
    `ingested_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `Fixture_sport_alias_idx`(`sport_alias`),
    INDEX `Fixture_competition_id_idx`(`competition_id`),
    INDEX `Fixture_start_time_idx`(`start_time`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
